const data = {
  products: [
    {
      name: 'Nike Shirts',
      slug: 'nike-shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numRewiews: 10,
      description: 'High quality shirts',
    },
    {
      name: 'Adidas Shirts',
      slug: 'adidas-shirts',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 220,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.9,
      numRewiews: 10,
      description: 'High quality shirts',
    },
    {
      name: 'Nike pants',
      slug: 'nike-pants',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numRewiews: 10,
      description: 'High quality pants',
    },
    {
      name: 'Adidas pants',
      slug: 'adidas-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 90,
      countInStock: 10,
      brand: 'adidas',
      rating: 4.5,
      numRewiews: 10,
      description: 'High quality pants',
    },
  ],
};

export default data;
